# CIPP Frontend Deployment for Render.com
#
# IMPORTANT: CIPP requires an Azure backend (CIPP-API) because it uses PowerShell Azure Functions.
# This configuration deploys the frontend on Render, which proxies API requests to your Azure backend.
#
# Before deploying:
# 1. Deploy CIPP-API to Azure first (see: https://docs.cipp.app/setup/self-hosting-guide/install)
# 2. Set CIPP_API_URL to your Azure Functions URL (e.g., https://your-cipp-api.azurewebsites.net)
#
# For full setup instructions, see: https://docs.cipp.app

services:
  - type: web
    name: cipp-frontend
    runtime: node
    plan: free
    # Custom build - don't use 'npm run build' as it deletes package.json (designed for Azure SWA)
    buildCommand: npm install && npx next build
    startCommand: npx next start
    envVars:
      # REQUIRED: Your Azure CIPP-API Functions URL
      # Example: https://cipp-api-xxxxx.azurewebsites.net
      - key: CIPP_API_URL
        sync: false
      # Render sets this automatically - used to detect Render environment
      - key: RENDER
        value: "true"
      # Node environment
      - key: NODE_ENV
        value: production
